# Generated by Django 5.1.1 on 2024-10-10 02:04

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='page',
        ),
        migrations.RemoveField(
            model_name='author',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='talkpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(to='talk.author'),
        ),
    ]
