# Generated by Django 5.1.1 on 2024-10-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
