# Generated by Django 5.1.1 on 2024-11-07 04:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_relatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('paragraph', 1)]], {})}, default=''),
            preserve_default=False,
        ),
    ]
